name: the_billion_dollar_goat
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  chat_gpt_sdk: ^2.1.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  go_router: ^6.5.9
  path_provider: ^2.0.14
  record: ^4.4.4

dev_dependencies:
  amplify_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
