name: the_billion_dollar_goat
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  amplify_api: ^1.3.0
  amplify_flutter: ^1.3.0
  chat_gpt_sdk: ^2.1.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  go_router: ^6.5.9
  path_provider: ^2.0.14
  record: ^4.4.4

dependency_overrides:
  amplify_api:
    path: ../ad-config/packages/api/amplify_api
  amplify_api_dart:
    path: ../ad-config/packages/api/amplify_api_dart
  amplify_core:
    path: ../ad-config/packages/amplify_core
  amplify_flutter:
    path: ../ad-config/packages/amplify/amplify_flutter
  aws_common:
    path: ../ad-config/packages/aws_common

dev_dependencies:
  amplify_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
